# Longest-first replacement pairs: RU -> EN for about-service presentation.
PAIRS_EXTRA: list[tuple[str, str]] = [
    (
        "Персонаж — это ваша виртуальная модель целиком: внешность, характер, история и каналы, к которым она привязана. Всё остальное в сервисе ссылается на неё.",
        "A character is your full virtual model: look, personality, backstory, and the channels she is tied to. Everything else in the service links back to her.",
    ),
    ("Не папка с картинками, а личность", "Not a folder of images, but a persona"),
    (
        "<b>Фото и внешность</b> — референсы и текстовое описание, которое едет в каждую генерацию",
        "<b>Photos and look</b> — references and a text description that flows into every generation",
    ),
    (
        "<b>Персона</b> — то, чем AI отвечает фану, когда оператор спит",
        "<b>Persona</b> — what AI uses to reply when the operator is asleep",
    ),
    (
        "<b>EXIF</b> — метаданные и гео, как будто снято на её телефон",
        "<b>EXIF</b> — metadata and geo as if shot on her phone",
    ),
    (
        "<b>История</b> — что делали с моделью и сколько кредитов ушло",
        "<b>History</b> — what happened with the model and how many credits were spent",
    ),
    ("Персонаж · EXIF", "Character · EXIF"),
    ("Персонаж · Внешность", "Character · Look"),
    ("Персонаж · Персона", "Character · Persona"),
    (">Персонаж<", ">Character<"),
    (
        "Кадр, который выглядит<br>как снятый на телефон",
        "A frame that looks<br>like a phone shot",
    ),
    (
        "Загружаете два эталона со своего телефона — фронтальную и основную камеру. Сервис переносит их характер съёмки на сохранённые кадры студии: зерно, JPEG-сжатие и метаданные. Плюс координаты города персонажа.",
        "Upload two references from your phone — front and main camera. The service applies their shooting character to saved studio frames: grain, JPEG compression, and metadata. Plus the character city coordinates.",
    ),
    (
        "Берётся пресет камеры из списка — настраивается один раз",
        "Pick a camera preset from the list — configure once",
    ),
    (
        "Фронталка или основная <b>выбирается при каждой генерации</b> — селфи и обычное фото отличаются",
        "Front or main camera <b>is chosen on each generation</b> — selfies and regular photos differ",
    ),
    ("<b>10 кр</b>", "<b>10 cr</b>"),
    ("<b>8 кр</b>", "<b>8 cr</b>"),
    ("<b>8 кр за кадр</b>", "<b>8 cr per frame</b>"),
    ("<b>40 кредитов</b>", "<b>40 credits</b>"),
    (
        "<b>Первый кадр</b> — из архива студии или свой файл",
        "<b>First frame</b> — from studio archive or your own file",
    ),
    ("<b>Референс</b> — MP4 до 30 секунд", "<b>Reference</b> — MP4 up to 30 seconds"),
    (
        "<b>Качество</b> — 720p, 1080p или 4K, 5 или 10 секунд",
        "<b>Quality</b> — 720p, 1080p or 4K, 5 or 10 seconds",
    ),
    (
        "<b>40 кредитов</b> за ролик, скачивание в MP4",
        "<b>40 credits</b> per clip, download as MP4",
    ),
    ("Все площадки<br>в одном инбоксе", "All platforms<br>in one inbox"),
    (
        "Пишете по-русски —<br>фан читает на своём",
        "You write in Russian —<br>the fan reads in theirs",
    ),
    (
        "<b>Telegram</b> — несколько ботов, у каждого свой персонаж и своя задержка",
        "<b>Telegram</b> — multiple bots, each with its own character and delay",
    ),
    ("<b>Fanvue</b> — подключение аккаунта по OAuth", "<b>Fanvue</b> — OAuth account connection"),
    (
        "<b>WaveSpeed</b> — движок генераций; на Pro можно подставить свой ключ и не тратить кредиты",
        "<b>WaveSpeed</b> — generation engine; on Pro you can use your own key and skip credits",
    ),
    (
        "<b>Tribute</b> — свой аккаунт для донатов и платных чатов",
        "<b>Tribute</b> — your own account for donations and paid chats",
    ),
    (
        "<b>Уведомления</b> — push в браузер о новых сообщениях и донатах",
        "<b>Notifications</b> — browser push for new messages and donations",
    ),
    ("Донаты и выплаты<br>внутри сервиса", "Donations and payouts<br>inside the service"),
    (
        "Подписка — за места,<br>кредиты — за генерации",
        "Subscription — for seats,<br>credits — for generations",
    ),
    ("Workflow — цепочка<br>в один клик", "Workflow — pipeline<br>in one click"),
    (
        "<b>Один и тот же человек</b> у всех операторов и во всех режимах студии",
        "<b>The same person every time</b> for all operators and across studio modes",
    ),
    ("Personaж · EXIF", "Character · EXIF"),
    ("alt=\"Список персонажей\"", "alt=\"Character list\""),
    ("alt=\"Фото-референсы и описание внешности\"", "alt=\"Photo references and look description\""),
    ("alt=\"Настройка EXIF\"", "alt=\"EXIF settings\""),
    ("alt=\"Список диалогов\"", "alt=\"Dialog list\""),
    ("alt=\"Подключения\"", "alt=\"Connections\""),
    ("alt=\"Команда\"", "alt=\"Team\""),
    ("alt=\"Тарифы\"", "alt=\"Pricing\""),
    ("Диалоги", "Dialogs"),
    ("Команда", "Team"),
    ("Деньги", "Money"),
    ("Дальше", "Next"),
    ("Итог", "Summary"),
    ("btn.textContent='анимация · '+(mode==='full'?'вкл':'выкл');", "btn.textContent='motion · '+(mode==='full'?'on':'off');"),
    ('type="button" aria-pressed="true">анимация · вкл</button>', 'type="button" aria-pressed="true">motion · on</button>'),
    ("<h3>Кадр</h3>", "<h3>Frame</h3>"),
    ("<h3>Видео</h3>", "<h3>Video</h3>"),
    ("<h3>Канал</h3>", "<h3>Channel</h3>"),
    ("<h3>Диалог</h3>", "<h3>Dialog</h3>"),
    ("<h3>Деньги</h3>", "<h3>Money</h3>"),
    ("<h3>Персонаж</h3>", "<h3>Character</h3>"),
    (
        "Персонаж — это ваша виртуальная модель целиком: внешность, характер, история и каналы, к которым она привязана. Всё остальное в сервисе ссылается на неё",
        "A character is your full virtual model: look, personality, backstory, and the channels she is tied to. Everything else in the service links back to her",
    ),
    (
        "Не папка с картинками, а личность с референсами и текстовым описанием, которое едет в каждую генерацию",
        "Not a folder of images, but a persona with references and a text description that flows into every generation",
    ),
    (
        "Загружаете референсы и размечаете их тегами: лицо, внешность, развёртка, тело целиком, селфи, основная камера. Описание внешности можно собрать из фото одной кнопкой",
        "Upload references and tag them: face, look, turnaround, full body, selfie, main camera. You can assemble the look description from photos in one click",
    ),
    (
        "Возраст, город, часовой пояс, характер, хобби, темы для разговора, образ жизни, стиль переписки и предыстория. Это не анкета для галочки — на этом работает AI-компаньон в диалогах",
        "Age, city, timezone, personality, hobbies, conversation topics, lifestyle, chat style, and backstory. Not a checkbox form — the AI companion in dialogs runs on this",
    ),
    ("Персонаж · Персона", "Character · Persona"),
    ("Персонаж · Внешность", "Character · Look"),
    ("Одно лицо во всех кадрах", "One face across every frame"),
    ("Один и тот же человек", "The same person every time"),
    ("Кадр, который выглядит как снятый на телефон", "A frame that looks phone-shot"),
    ("как снятый на телефон", "like a phone shot"),
    ("Студия · Картинки", "Studio · Images"),
    ("Студия · Видео", "Studio · Video"),
    ("Семь режимов вместо пустого промпта", "Seven modes instead of an empty prompt"),
    (
        "Фан просит не «изображение девушки», а конкретную вещь: то же самое, но в другом платье; та же поза, но на пляже; серию для сторис. Под каждый запрос — свой режим с подсказками внутри",
        "Fans do not ask for a generic image — they want the same shot in another dress, the same pose on a beach, a story series. Each request gets its own guided mode",
    ),
    ("Кадр по референсу", "Frame from reference"),
    ("Кадр по промпту", "Frame from prompt"),
    ("Смена локации", "Change location"),
    ("Замена одежды", "Outfit swap"),
    ("Перенести в новое место", "Move to a new place"),
    ("Одежда с фото → на персонажа", "Outfit from photo → onto character"),
    ("Поза, свет и стиль по образцу", "Pose, light, and style from reference"),
    ("Лицо персонажа на готовый кадр", "Character face on a ready frame"),
    ("Face Swap", "Face Swap"),
    ("Свободная генерация с нуля", "Free generation from scratch"),
    ("Связанная серия из одного фото — для постов и историй", "Linked series from one photo — for posts and stories"),
    ("Карусель", "Carousel"),
    ("Точечная правка элемента", "Targeted element edit"),
    ("Изменить детали", "Change details"),
    ("Режим 01 · Отключён", "Mode 01 · Off"),
    ("Режим 02 · Полуавтомат", "Mode 02 · Semi-auto"),
    ("Режим 03 · Автоматически", "Mode 03 · Automatic"),
    (
        "Режим сам берёт нужный тип фото: для Face Swap — лицо, для полного кадра — развёртку",
        "The mode picks the right photo type: face for Face Swap, turnaround for a full frame",
    ),
    ("Если эталонов нет", "If you have no references"),
    (
        "Загружаете два эталона со своего телефона — фронтальную и основную камеру. Сервис переносит их характер съёмки на сохранённые кадры студии: зерно, JPEG-сжатие и метаданные. Плюс координаты города персонажа",
        "Upload two references from your phone — front and main camera. The service applies their shooting character to saved studio frames: grain, JPEG compression, and metadata. Plus the character city coordinates",
    ),
    (
        "метаданные и гео, как будто снято на её телефон",
        "metadata and geo as if shot on her phone",
    ),
    ("селфи и обычное фото отличаются", "selfies and regular photos differ"),
    ("Фронталка или основная", "Front or main camera"),
    ("Персона · EXIF", "Persona · EXIF"),
    ("Кадры, которые проходят<br>проверку на «нейронку»", "Frames that pass<br>the AI sniff test"),
    (
        "Генерация без эталонов на телефоне выглядит «чистой». Здесь сервис накладывает шум, JPEG-артефакты и EXIF. Фан открывает свойства файла и видит знакомую картину",
        "Generation without phone references looks too clean. Here the service adds noise, JPEG artifacts, and EXIF. Fans open file properties and see a familiar picture",
    ),
    ("Поле «город съёмки»", "Shoot city field"),
    ("Гео подставляется автоматически", "Geo is filled in automatically"),
    ("Студия · EXIF", "Studio · EXIF"),
    ("Студия · Архив", "Studio · Archive"),
    (
        "Кадры и ролики лежат в архиве около четырёх дней — важное лучше скачивать сразу",
        "Frames and clips stay in the archive for about four days — download what matters right away",
    ),
    (
        "Берёте готовый кадр из архива — и описываете движение словами или показываете его референсным видео. Motion Control повторит движение из вашего ролика, режим по промпту сделает своё",
        "Take a ready frame from the archive and describe motion in words or show reference video. Motion Control repeats movement from your clip; prompt mode creates its own",
    ),
    ("Кадр начинает двигаться", "The frame starts moving"),
    ("до 30 секунд", "up to 30 seconds"),
    ("или 4K, 5 или 10 секунд", "or 4K, 5 or 10 seconds"),
    ("за ролик, скачивание в", "per clip, download to"),
    ("м 12 с", "m 12 s"),
    ("Диалоги · Настройки", "Dialogs · Settings"),
    ("Все площадки в одном инбоксе", "All platforms in one inbox"),
    (
        "Telegram, Fanvue, Threads и Instagram — общий список с фильтрами: VIP, рабочие, новые, без ответа больше суток. Видно, кто заблокировал или удалил чат",
        "Telegram, Fanvue, Threads, and Instagram — one list with filters: VIP, active, new, no reply for 24h+. See who blocked or deleted the chat",
    ),
    ("Пишете по-русски", "You write in Russian"),
    (
        "Язык определяется автоматически по сообщениям фана, при желании закрепляется вручную. Оператор не выходит из чата и не теряет интонацию",
        "Language is detected from fan messages and can be pinned manually. The operator stays in chat without losing tone",
    ),
    ("фан читает на своём", "the fan reads in theirs"),
    ("Досье фана", "Fan dossier"),
    (
        "Профиль, контекст переписки и рекомендация: что человек хочет, что ему обещали, сколько платил",
        "Profile, chat context, and recommendations: what they want, what was promised, how much they paid",
    ),
    ("анализ и заметки", "analysis and notes"),
    (
        "Одна кнопка — и вся история диалога сворачивается в короткую сводку для оператора",
        "One button collapses the full chat into a short operator summary",
    ),
    ("Характер, который отвечает за неё", "The personality that speaks for her"),
    ("Отвечаете только вы. AI не вмешивается", "Only you reply. AI stays out"),
    ("оператор правит и отправляет", "operator edits and sends"),
    ("предлагает ответ", "suggests a reply"),
    ("отвечает сам по персоне модели — ночью и в пересменок", "replies on its own from the model persona — at night and between shifts"),
    (
        "Задержка ответа 5–45 секунд и лимит автоответов в час: переписка не выглядит как бот",
        "5–45 second reply delay and hourly auto-reply cap: the chat does not feel like a bot",
    ),
    (
        "Плюс общие шаблоны ответов — приветствие VIP, оффер видео — чтобы новичок не выдумывал с нуля",
        "Plus shared reply templates — VIP hello, video offer — so newcomers do not start from zero",
    ),
    ("Стиль переписки", "Chat style"),
    ("Темы для разговора", "Conversation topics"),
    ("Оценка AI-ответов", "AI reply ratings"),
    ("лайков от операторов", "likes from operators"),
    ("Подключения за минуту", "Connections in minutes"),
    (
        "Создаёте бота у BotFather, вставляете токен — вебхук настроится сам. Дальше привязываете персонажа и решаете, включать ли автоответы",
        "Create a bot in BotFather, paste the token — webhook sets itself up. Then bind a character and choose whether auto-replies are on",
    ),
    ("Канал подключается за минуту", "A channel connects in a minute"),
    ("Подключения", "Connections"),
    ("в один клик", "in one click"),
    ("подключение аккаунта по @username", "@username account connection"),
    ("Диалоги в работе, существующие коннекты уже видны в списке", "Active dialogs; existing connections already show in the list"),
    ("Команда · Права", "Team · Access"),
    (
        "Права расставляются галочками: диалоги, студия, персонажи, ключи интеграций, оплата. Отдельно — доступ к конкретным моделям",
        "Permissions by checkbox: dialogs, studio, characters, integration keys, billing. Plus access to specific models",
    ),
    ("Операторы под контролем", "Operators under control"),
    ("по всей команде", "across the team"),
    ("Ответы за месяц", "Replies this month"),
    ("что делали с моделью и сколько кредитов ушло", "what happened with the model and how many credits were spent"),
    ("Визуальный конструктор цепочек", "Visual pipeline builder"),
    (
        "Узловой редактор для тех, кто повторяет одно и то же каждый день: генерация → свап → постобработка → карусель. Собрали один раз — запускаете кнопкой",
        "Node editor for daily repeat work: generate → swap → post-process → carousel. Build once — run with a button",
    ),
    ("Донаты и выплаты", "Donations & payouts"),
    ("Деньги · Тарифы", "Money · Plans"),
    ("Тариф и баланс", "Plan & balance"),
    (
        "Тариф открывает операторов и персонажей. Кредиты тратятся только тогда, когда вы что-то генерируете",
        "Plans unlock operators and characters. Credits are spent only when you generate something",
    ),
    ("Подписка — за места", "Subscription — for seats"),
    ("кредиты — за генерации", "credits — for generations"),
    ("оператор · 3 персонажа · кредиты на студию включены", "operator · 3 characters · studio credits included"),
    ("операторов · 10 персонажей · чат и команда · кредиты включены", "operators · 10 characters · chat & team · credits included"),
    ("Безлимит операторов · 30 персонажей · приоритетная поддержка", "Unlimited operators · 30 characters · priority support"),
    ("на Pro-тарифе", "on Pro plan"),
    (
        "движок генераций; на Pro можно подставить свой ключ и не тратить кредиты",
        "generation engine; on Pro you can use your own key and skip credits",
    ),
    ("Свой ключ", "Your own key"),
    ("без списания кредитов", "without spending credits"),
    (
        "Оплата картой, кредитами или через Tribute. Пакеты кредитов от 100 до 1500 с бонусом до 15%. За приглашённого друга — 25 кредитов и 10% с его оплат",
        "Pay by card, credits, or Tribute. Credit packs from 100 to 1500 with up to 15% bonus. Refer a friend — 25 credits and 10% of their payment",
    ),
    ("Комиссия сервиса", "Service fee"),
    ("с доната, приём через Tribute-аккаунт ModelMate", "of each donation, collected via ModelMate Tribute account"),
    (
        "Под каждый повод — своя ссылка: «Поддержать Mia», «Платье для съёмки», регулярная подписка. Ссылка сразу в двух видах: для Telegram и для веба",
        "Each occasion gets its own link: Support Mia, Shoot dress, recurring subscription. Link in two forms: Telegram and web",
    ),
    ("свой аккаунт для донатов и платных чатов", "your own account for donations and paid chats"),
    ("Доля", "Share"),
    ("оператора", "operator"),
    ("и доля с донатов в процентах", "and donation share in percent"),
    ("Вывод", "Payout"),
    ("или TON, от", "or TON, from"),
    ("Прозрачность", "Transparency"),
    ("Видно всего, доступно, на удержании и выплачено", "See total, available, on hold, and paid out"),
    ("внутри сервиса", "inside the service"),
    ("площадки в одном инбоксе", "platforms in one inbox"),
    ("режимов съёмки кадра", "frame shoot modes"),
    ("режима автоответчика", "auto-reply modes"),
    ("комиссия с донатов", "donation fee"),
    ("Зачем теги", "Why tags matter"),
    ("Фото и внешность", "Photos and look"),
    ("Предыстория", "Backstory"),
    ("Город и часовой пояс", "City and timezone"),
    (
        "Часовой пояс важнее, чем кажется: модель из Мадрида не пишет «доброе утро» в четыре ночи по своему времени",
        "Timezone matters more than it seems: a Madrid model does not say good morning at 4 AM her time",
    ),
    ("Первый кадр", "First frame"),
    ("Первый ответ", "First reply"),
    ("Первый кадр —", "First frame —"),
    ("Уведомления", "Notifications"),
    ("в браузер о новых сообщениях и донатах", "in the browser for new messages and donations"),
    ("и для веба", "and for web"),
    ("Дальше", "Next"),
    ("Генерации", "Generations"),
    ("кр за кадр", "cr per frame"),
    ("кредитов", "credits"),
    ("кредит", "credit"),
    ("в среднем", "on average"),
    ("мес", "mo"),
    ("цепочка", "pipeline"),
    ("на подключении", "on the connection"),
    ("выбирается при каждой генерации", "chosen on each generation"),
    ("Задаётся", "Set"),
    ("для каждого", "for each"),
    ("несколько ботов, у каждого свой персонаж и своя задержка", "multiple bots, each with its own character and delay"),
    (
        "Берётся пресет камеры из списка — настраивается один раз и используется у всех операторов и во всех режимах студии",
        "Pick a camera preset from the list — configure once and use across operators and studio modes",
    ),
    ("без сведения таблиц", "without spreadsheet hell"),
    ("Результат", "Result"),
    ("Качество", "Quality"),
    ("Камера", "Camera"),
    ("Референс", "Reference"),
    ("История", "Backstory"),
    ("Характер", "Personality"),
    ("Хобби", "Hobbies"),
    ("Возраст", "Age"),
    ("Персона", "Persona"),
    ("автоответы", "auto-replies"),
    ("анимация включена по умолчанию", "animation on by default"),
    (
        "подсказка, если в системе «уменьшение движения",
        "hint if the system has reduce motion enabled",
    ),
]
